plugins:
  fixme:
    enabled: true
    config:
      strings:
      - DEBUG
      - HACK
      - TODO
      - FIXME
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .eslintrc
      extensions:
      - .js
exclude_patterns:
- "**/node_modules/"
- "dist/"
- "source/**/*.test.js"
- "source/**/*.bench.js"
- "benchRunner.js"
